### PR TITLE
Create API: Add redirect and select newest created API

### PR DESCRIPTION
**Pull request by christiemolloy**
Once an API is created, the application redirects to the home page and on the home page the newest created API is selected. Test this by creating a new API and making sure that it 1) redirects to the page, 2) the newest API is selected, 3) when you click on another API the selection changes to that API. And test for anything else you would expect.

### CODE REVIEW

**Comment by EricWittmann** [comment]
If the list of APIs is long, does the selected API get scrolled to?  Or does it not matter because it's selected and the panel on the right is active?

**Comment by christiemolloy** [comment]
@EricWittmann Good question, that was something I was planning on bringing up. I was thinking we should talk with design about how the actual ID's are ordered by default, maybe they should be ordered by time stamp so that the new API would appear at the top. Otherwise I could have the page scroll to that API but that seems not as intuitive.

**Comment by lboehling** [comment]
@christiemolloy @EricWittmann I think it would be a good idea to default sort by timestamp. After you create an AP then, it would take you back to the list with the new API in the first row and selected, correct? Does ordering by time only apply to the date the API was created or does it order by most recently edited too?

**Comment by EricWittmann** [comment]
It's easy to sort by creation date, but not by last modified.  The back-end would need to be modified to support a sort by last-modified.  I'm not sure the complexity offhand.

**Comment by christiemolloy** [comment]
@lboehling @EricWittmann I think ordering by timestamp is a good idea, atleast for now that will help with showing the first API at the top of the data list right after its created. We could always look into the "date last edited" in the future.

**Comment by christiemolloy** [comment]
@lboehling @EricWittmann I created a follow-up issue to order the APIs by timestamp https://issues.redhat.com/browse/APPDUX-239

Let me know if you have any other feedback

**Pull request merged**
